"""Initial migration

Revision ID: 7d25f1a8921a
Revises: 8ee405955ed1
Create Date: 2025-01-23 23:58:00.368942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d25f1a8921a'
down_revision = '8ee405955ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_record', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.TIME(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doc_record', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Text(),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
