"""Initial migration

Revision ID: 93681e1770ef
Revises: 7d25f1a8921a
Create Date: 2025-01-25 14:06:17.183066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93681e1770ef'
down_revision = '7d25f1a8921a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pat_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('disease', sa.String(length=100), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pat_record')
    # ### end Alembic commands ###
